# Translations template for neutron-vpnaas.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the neutron-vpnaas
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron-vpnaas 8.0.0.0b2.dev16\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-12-13 05:32-0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: neutron_vpnaas/db/vpn/vpn_validator.py:295
msgid "Invalid CIDR"
msgstr ""

#: neutron_vpnaas/db/vpn/vpn_validator.py:304
msgid "Invalid UUID"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:31
#, python-format
msgid "VPNService %(vpnservice_id)s could not be found"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:35
#, python-format
msgid "ipsec_site_connection %(ipsec_site_conn_id)s not found"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:39
#, python-format
msgid "ipsec_site_connection %(attr)s is equal to or less than dpd_interval"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:44
#, python-format
msgid "ipsec_site_connection MTU %(mtu)d is too small for ipv%(version)s"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:49
#, python-format
msgid "IKEPolicy %(ikepolicy_id)s could not be found"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:53
#, python-format
msgid "IPsecPolicy %(ipsecpolicy_id)s could not be found"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:57
#, python-format
msgid ""
"IKEPolicy %(ikepolicy_id)s is in use by existing IPsecSiteConnection and "
"can't be updated or deleted"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:62
#, python-format
msgid "VPNService %(vpnservice_id)s is still in use"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:66
#, python-format
msgid "Subnet %(subnet_id)s is used by VPNService %(vpnservice_id)s"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:70
#, python-format
msgid "Subnet %(subnet_id)s is used by endpoint group %(group_id)s"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:74
#, python-format
msgid "Invalid state %(state)s of vpnaas resource %(id)s for updating"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:79
#, python-format
msgid ""
"IPsecPolicy %(ipsecpolicy_id)s is in use by existing IPsecSiteConnection "
"and can't be updated or deleted"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:84
#, python-format
msgid "Can not load driver :%(device_driver)s"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:88
#, python-format
msgid "Subnet %(subnet_id)s is not connected to Router %(router_id)s"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:93
#, python-format
msgid "Router %(router_id)s has no external network gateway set"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:97
#, python-format
msgid "Peer address %(peer_address)s cannot be resolved"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:101
#, python-format
msgid "Router's %(router_id)s external network has no %(ip_version)s subnet"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:106
#, python-format
msgid "Endpoint group %(endpoint_group_id)s could not be found"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:110
#, python-format
msgid ""
"Endpoint '%(endpoint)s' is invalid for group type '%(group_type)s': "
"%(why)s"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:115
#, python-format
msgid "No endpoints specified for endpoint group '%(group)s'"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:119
#, python-format
msgid "Subnet %(subnet)s in endpoint group does not exist"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:123
#, python-format
msgid ""
"Endpoints in group %(group)s do not have the same IP version, as required"
" for IPSec site-to-site connection"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:128
msgid ""
"Peer CIDRs do not have the same IP version, as required for IPSec site-"
"to-site connection"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:133
msgid "IP versions are not compatible between peer and local endpoints"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:138
#, python-format
msgid ""
"Endpoint group%(suffix)s %(which)s cannot be specified, when VPN Service "
"has subnet specified"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:143
#, python-format
msgid ""
"Endpoint group %(which)s type is '%(group_type)s' and should be "
"'%(expected)s'"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:148
msgid "Peer CIDRs cannot be specified, when using endpoint groups"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:153
msgid "Missing peer CIDRs for IPsec site-to-site connection"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:157
#, python-format
msgid ""
"Missing endpoint group%(suffix)s %(which)s for IPSec site-to-site "
"connection"
msgstr ""

#: neutron_vpnaas/extensions/vpnaas.py:162
#, python-format
msgid "Endpoint group %(group_id)s is in use and cannot be deleted"
msgstr ""

#: neutron_vpnaas/services/vpn/agent.py:40
#: neutron_vpnaas/services/vpn/vyatta_agent.py:29
msgid "The vpn device drivers Neutron will use"
msgstr ""

#: neutron_vpnaas/services/vpn/common/netns_wrapper.py:42
msgid "Dict of paths to bind-mount (source:target) prior to launch subprocess."
msgstr ""

#: neutron_vpnaas/services/vpn/common/netns_wrapper.py:47
msgid ""
"Command line to execute as a subprocess provided as comma-separated list "
"of arguments."
msgstr ""

#: neutron_vpnaas/services/vpn/common/netns_wrapper.py:50
msgid "Rootwrap configuration file."
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/cisco_ipsec.py:39
msgid "Status check interval for Cisco CSR IPSec connections"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/cisco_ipsec.py:50
#, python-format
msgid "Cisco CSR failed to create %(resource)s (%(which)s)"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/cisco_ipsec.py:54
#, python-format
msgid "Cisco CSR failed to change %(tunnel)s admin state to %(state)s"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/cisco_ipsec.py:59
#, python-format
msgid ""
"Required %(resource)s attribute %(attr)s mapping for Cisco CSR is missing"
" in device driver"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/cisco_ipsec.py:64
#, python-format
msgid ""
"Device driver does not have a mapping of '%(value)s for attribute "
"%(attr)s of %(resource)s"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:51
msgid "Location to store ipsec server config files"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:54
msgid "Interval for checking ipsec status"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:57
msgid ""
"Enable detail logging for ipsec pluto process. If the flag set to True, "
"the detailed logging will be written into config_base_dir/<pid>/log. "
"Note: This setting applies to OpenSwan and LibreSwan only. StrongSwan "
"logs to syslog."
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:71
msgid "Template file for ipsec configuration"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:77
msgid "Template file for ipsec secret configuration"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:85
msgid "Initial interval in seconds for checking if pluto daemon is shutdown"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:90
msgid "The maximum number of retries for checking for pluto daemon shutdown"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/ipsec.py:95
msgid "A factor to increase the retry interval for each retry"
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/strongswan_ipsec.py:33
msgid "Template file for ipsec configuration."
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/strongswan_ipsec.py:39
msgid "Template file for strongswan configuration."
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/strongswan_ipsec.py:45
msgid "Template file for ipsec secret configuration."
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/strongswan_ipsec.py:51
msgid "The area where default StrongSwan configuration files are located."
msgstr ""

#: neutron_vpnaas/services/vpn/device_drivers/vyatta_ipsec.py:252
msgid "Router id={0} have no external gateway."
msgstr ""

#: neutron_vpnaas/services/vpn/service_drivers/cisco_csr_db.py:44
#, python-format
msgid "Fatal - %(reason)s"
msgstr ""

#: neutron_vpnaas/services/vpn/service_drivers/cisco_csr_db.py:78
#, python-format
msgid "No available Cisco CSR %(type)s IDs from %(min)d..%(max)d"
msgstr ""

#: neutron_vpnaas/services/vpn/service_drivers/cisco_csr_db.py:133
#, python-format
msgid ""
"Database inconsistency between IPSec connection and Cisco CSR mapping "
"table (%s)"
msgstr ""

#: neutron_vpnaas/services/vpn/service_drivers/cisco_csr_db.py:196
#, python-format
msgid ""
"Existing entry for IPSec connection %s not found in Cisco CSR mapping "
"table"
msgstr ""

#: neutron_vpnaas/services/vpn/service_drivers/cisco_csr_db.py:223
#, python-format
msgid ""
"Attempt to create duplicate entry in Cisco CSR mapping table for "
"connection %s"
msgstr ""

#: neutron_vpnaas/services/vpn/service_drivers/cisco_validator.py:32
#, python-format
msgid ""
"Cisco CSR does not support %(resource)s attribute %(key)s with value "
"'%(value)s'"
msgstr ""

#: neutron_vpnaas/services/vpn/service_drivers/ipsec_validator.py:21
#, python-format
msgid ""
"IPSec does not support %(resource)s attribute %(key)s with value "
"'%(value)s'"
msgstr ""

